### ISSUE TITLE
Hitbox issues + slow block breaking

### ISSUE THREAD

**Issue by Greenjoe12345** [Lyinginbedmon/Wheelchairs-2#10]
Version 2.51 on Fabric 1.20.1, the mounted height of the player makes it difficult to get through 2 block high gaps, requiring sneaking to do so.
In addition, the wheelchair's hitbox width makes it impossible to move through a single doorway.
When breaking blocks while using a wheelchair, it takes far longer to do so then on foot, carrying over from the normal mounted block breaking slowdown
![image](https://github.com/user-attachments/assets/6e3b9fe6-5c3c-4194-9719-e28eed978404)

**Comment by Lyinginbedmon** [comment]
Ah, these are problems that occurred in the 1.20.4 versions that evidently didn't get resolved in the backport before release. Good catch
