### ISSUE TITLE
After installing the author's mod, the elevator that causes this mod to rise and fall without animation

### ISSUE THREAD

**Issue by LimitXiaoHuoChai** [Lyinginbedmon/Wheelchairs-2#11]
Game version: 1.20.1, 
mod version:wheelchairs-fabric-2.53-1.20.2，
moving-elevators：
https://modrinth.com/mod/moving-elevators

**Comment by Lyinginbedmon** [comment]
This is most likely related to how Moving Elevators manages elevator movement, particularly when with ridden entities. Please report this issue to the author of that project.
