### ISSUE TITLE
Error opening mod

### ISSUE THREAD

**Issue by KidneyToadpool** [Lyinginbedmon/Wheelchairs-2#2]
While trying to run the mod I keep encountering the error:

The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'wheelchairs'!

It gave this error regardless of what version of fabric api I used and regardless of if I had other mods running or not, if theres an obvious solution I haven't found it yet.

I am playing in 1.20.6 with fabric version 0.15.11

**Comment by Lyinginbedmon** [comment]
Could you provide the full crash log?

**Comment by KidneyToadpool** [comment]
[crash-2024-05-24_18.26.29-client.txt](https://github.com/Lyinginbedmon/Wheelchairs-2/files/15440568/crash-2024-05-24_18.26.29-client.txt)

**Comment by Lyinginbedmon** [comment]
I've managed to replicate the error and looks like there were some compiling changes made for 1.20.6 that are causing issues. I'll need to recompile a new release for the later version but I can at least confirm that the mod works just fine in 1.20.4.
