### ISSUE TITLE
Cane & Wheel Crafting Broken

### ISSUE THREAD

**Issue by dawn-path** [Lyinginbedmon/Wheelchairs-2#4]
Love the mod! - but cannot craft canes or wheels properly. Cane heads apply correctly, but all canes regardless of wood type craft with "Handle: Oak Cane", not even "Handle: Oak", and render with the oak cane texture. Canes taken from the creative menu display properly. Additionally, following the wiki's wheel recipe, no wheels can be crafted at all. Wheelchairs crafted with wheels taken from the creative inventory craft successfully and behave as expected. I have tested all of this without any mods aside from Wheelchairs, Fabric, and Fabric API installed.

No issues with crutches, though, nor dyeing. Delighted with the new additions and can't wait to use them!

![2024-06-05_19 46 50](https://github.com/Lyinginbedmon/Wheelchairs-2/assets/171888045/43459c18-914e-4412-bfdb-05790cf54c51)

**Comment by Lyinginbedmon** [comment]
Ah! I see where things went wrong here, I'll put out a hotfix to resolve this problem.

The cane/handle crafting problem is a bug, the wheels are just that the wiki was outdated.
