### ISSUE TITLE
Destructible after placement?

### ISSUE THREAD

**Issue by zachbryant** [Lyinginbedmon/Wheelchairs-2#5]
Hey there, would love to see if an update can be made to configure destructibility. I can imagine my server going nuts and placing a ton of these entities in one area. Not sure how else I'd get rid of them aside from removing the mod

**Comment by Lyinginbedmon** [comment]
They can be returned to item form by shift+right clicking when no-one is riding them, and otherwise are as vulnerable to /kill or falling into the void as any other entity.

**Comment by zachbryant** [comment]
With the carry-on mod installed, the only option is to throw into the void. This isn't possible without admin help. Any way we can get a configurable keybind to pick it up or some config to make them destructable?

**Comment by Lyinginbedmon** [comment]
Carry On includes a config setting to exclude specific entity types or all entities from a specific mod, for just such an occasion.
