### ISSUE TITLE
1.20.1 - Mod causes JEI, REI, and EMI to become completely nonfunctional

### ISSUE THREAD

**Issue by celestial-cookie** [Lyinginbedmon/Wheelchairs-2#7]
Mod version: 2.0.1 and 2.0.0 
Mod loader: Fabric
Game version: 1.20.1 (unable to test on 1.20.2)

(For clarification, im not talking about not being able to view the items in JEI/REI/EMI, but rather _all_ recipes for _all_ blocks in those mods become broken when Wheelchairs is present!) The mods in question appear to hit an error when parsing the recipes included in wheelchairs, causing JEI to shut down completely, REI to only load tags/anvil recipes/etc and no crafting recipes at all, and EMI to get stuck with the message "EMI is waiting for recipe data from the server..."

The error message that causes REI and EMI to break is actually also present in the log of an otherwise vanilla game, so I included a log without any of those mods. It's also present with JEI, but JEI shuts down before the error message appears.

The bug is not present on the 1.20.4 version of the mod, but I am unable to test it on 1.20.2. It is present in both 2.0.0 and 2.0.1.

[REI error log (1.20.1).txt](https://github.com/user-attachments/files/16385680/REI.error.log.1.20.1.txt)
[EMI error log (1.20.1).txt](https://github.com/user-attachments/files/16385681/EMI.error.log.1.20.1.txt)
[Vanilla error log (1.20.1).txt](https://github.com/user-attachments/files/16385682/Vanilla.error.log.1.20.1.txt)
[JEI error log (1.20.1).txt](https://github.com/user-attachments/files/16385683/JEI.error.log.1.20.1.txt)

**Comment by LimitXiaoHuoChai** [comment]
Thank you for your feedback, I also encountered the same bug

**Comment by Lyinginbedmon** [comment]
This seems to be related to the custom crafting recipes necessary to craft wheelchairs with custom wheels and canes with custom handles. The recipe mods are struggling to understand them, I'll see if I can find the miscommunication.

**Comment by Lyinginbedmon** [comment]
Problem identified and seemingly resolved. Will be remedied with the next backport release.

To explain, when a few of the recipes got backported from 1.20.4, they were providing their recipe type ID instead of their unique recipe ID. This caused the recipe system to think that there were multiple recipes with the same unique ID, and that broke the entire recipe catalogue instead of just discarding the faulty recipes.
