### ISSUE TITLE
1.20.2 - Unable to load any worlds

### ISSUE THREAD

**Issue by celestial-cookie** [Lyinginbedmon/Wheelchairs-2#8]
Mod version: 1.0, 2.0.0, 2.0.1
Mod loader: Fabric
Game version: 1.20.2 only

Upon clicking "Create a new world", the game crashes
[crash-2024-07-25_19.14.29-client.txt](https://github.com/user-attachments/files/16385776/crash-2024-07-25_19.14.29-client.txt)

Upon trying to load into an existing world, the game fails to load citing issues with "selected data packs", and when attempting to boot in safe mode says that the world contains invalid or corrupted data. (The save isn't actually corrupted, and can load properly again once wheelchairs is removed)
![image](https://github.com/user-attachments/assets/d3303a1a-418e-48ad-9a52-02df716ac662)
![image](https://github.com/user-attachments/assets/e0bd9a7d-6179-4c6d-a5c0-07ef263d6bcf)
[1.20.2 world loading error log.txt](https://github.com/user-attachments/files/16385812/1.20.2.world.loading.error.log.txt)

The same issue is present with wheelchairs 1.0 as well
[crash-2024-07-25_19.22.32-client.txt](https://github.com/user-attachments/files/16385821/crash-2024-07-25_19.22.32-client.txt)

**Comment by Lyinginbedmon** [comment]
This is most probably related to issue #7, a problem rooted in how the game is processing the custom crafting recipes necessary for customised wheels and cane handles. I'll look into it.

**Comment by Lyinginbedmon** [comment]
Issue #7 has been resolved and, as the solution pertained to datapack management as cited in this error, it is presumed that this issue is likewise resolved.
